### ISSUE TITLE
should we rename our specification documents to say katzenpost instead of panoramix?

### ISSUE THREAD

**Issue by david415** [katzenpost/mixnet_uprising#14]
If we are going to do a big rename we should at least discuss it a while first.
Maybe the researchers have an opinion. I mean... I'm should random people on the internet also have an opinion as well ;-) So what are the pros and cons?

**Comment by moba** [comment]
This is not a proposed "name change". PANORAMIX never was one messaging mixnet design; PANORAMIX always was a limited time collaboration research project between a defined set of entities. You can read more about it at www.panoramix-project.eu . It is a multi-year project, has a defined end as per grant agreement, and has a lot of participants who are simply not involved in the messaging use case. One of the many designs that was researched, in one of the areas of research within the PANORAMIX project that started in 2015, is the Loopix design, which in turn inspired the Katzenpost design in 2017, two years into the PANORAMIX project. Also see the respective terms in our Glossary.

The longer this rename does not happen, the more confusion it will create. You can already see this in this ticket and elsewhere. So, to me, the worry that this is creating confusion is exactly the reason why we need to do this "name fix" ASAP, and not a reason to keep the confusing name around even longer.

We have all the authority to make that decision, as a group who is actually interested in this project, and its continuation beyond the PANORAMIX research project. Actually it is the other way round: We have no authority to confusingly call this PANORAMIX, because PANORAMIX was a name already picked for a different thing altogether, which is collectively "owned" by more stakeholders for other things than messaging mixnets. It is our responsibility to decide on the name.

I totally agree that while we have the authority, it is nice to do this with collecting the input of all other participants. We even went beyond that, and asked other people for input on the naming as well; not only those that are part of the messaging deliverables/work package, and not only those that are part of PANORAMIX. We did have that conversation multiple times, and asking yet again for something that never should have been called PANORAMIX in the first place is wrong.

Sorry for the lack of visibility of these internals and the confusion it creates. Unfortunately, the full PANORAMIX project details cannot be publicly available, as some of the (non messaging mixnet related) industry research that is happening within the project is owned by SAP.

We can get over it simply by applying these changes. In fact, they have been applied to the to-be-authoritative ReStructuredText versions in the website repo, which can generate plaintext output which can totally replace the plaintext versions here.

**Comment by moba** [comment]
This is done now: https://github.com/katzenpost/docs/commit/20fb9cba33181754fa8b60c678039a2f0ef6567a
