### ISSUE TITLE
GSoC 2018 project ideas list

### ISSUE THREAD

**Issue by david415** [katzenpost/mixnet_uprising#35]
This is a list of project ideas for the Google Summer of Code, 2018:

- mix network simulations with ns-3: explore network performance and quality of service, resistance to DoS attacks, explore congestion control algorithms, ecn/source quench? prevent congestion collapse?

- implementation of https://github.com/katzenpost/docs/blob/master/drafts/kaetzchen.txt

**Comment by Yawning** [comment]
Hmm.

 * Investigate using SCTP with the partial reliability extension as a internal transport.  There's advantages to using something like this, but the security aspect of it is non-trivial.
 * katzenpost/core#11 (WIthout stuff like cgo).  Fairly difficult because the data structures involved are non-trivial (even if implemented elsewhere, and described in a paper) especially while trying to avoid impacting latency.
 * Investigate alternative wide-block ciphers to AEZv5 (https://eprint.iacr.org/2016/1188).  Might not be fast enough because AEZv5 is obnoxiously fast with hardware support, but the decrease in performance may be acceptable for the extra benefits (primarily higher security level).
 * The ever popular, "someone could/should write better unit/integration tests".
 * Make kimchi suck less: kimchi in our "integration test framework", essentially runs the entire mixnet in a single go process.

**Comment by Yawning** [comment]
Oh, "Design and implement (at least up to proof of concept level), an application that can utilize a medium latency mix network, that isn't e-mail.  Be creative.".

**Comment by moba** [comment]
Closing this in favor of [a wiki page](https://github.com/katzenpost/mixnet_uprising/wiki/Project-Ideas).
